version: 2.1
orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package-and-push-chart
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: alloy-gateway
        persist_chart_archive: true
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        context: architect
        name: push-to-capa-app-collection
        app_name: alloy-gateway
        app_namespace: monitoring
        app_collection_repo: capa-app-collection
        requires:
        - package-and-push-chart
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_name: alloy-gateway
        app_namespace: monitoring
        app_collection_repo: capz-app-collection
        requires:
        - package-and-push-chart
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-cloud-director-app-collection
        app_name: alloy-gateway
        app_namespace: monitoring
        app_collection_repo: cloud-director-app-collection
        requires:
        - package-and-push-chart
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: vsphere-app-collection
        context: architect
        app_name: alloy-gateway
        app_namespace: monitoring
        app_collection_repo: vsphere-app-collection
        requires:
        - package-and-push-chart
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
